expense/urls.py
from django.urls import path
from {PROJECT}.expense import views as v

app_name = 'expense'


urlpatterns = [
    path('', v.ExpenseListView.as_view(), name='expense_list'),
    path('<int:pk>/', v.expense_detail, name='expense_detail'),
    path('create/', v.expense_create, name='expense_create'),
    path('<int:pk>/update/', v.expense_update, name='expense_update'),
    path('<int:pk>/delete/', v.expense_delete, name='expense_delete'),
]

expense/models.py
from django.db import models
from django.urls import reverse_lazy
from {PROJECT}.core.models import TimeStampedModel
from {PROJECT}.crm.models import Person


class Expense(TimeStampedModel):
    description = models.CharField('descrição', max_length=50)
    payment_date = models.DateField('data de pagamento', null=True, blank=True)
    person = models.ForeignKey(
        Person,
        on_delete=models.SET_NULL,
        verbose_name='pago a',
        related_name='expenses',
        null=True,
        blank=True
    )
    value = models.DecimalField('valor', max_digits=7, decimal_places=2)
    paid = models.BooleanField('pago', default=False)

    class Meta:
        ordering = ('-payment_date',)
        verbose_name = 'despesa'
        verbose_name_plural = 'despesas'

    def __str__(self):
        return self.description

    def get_absolute_url(self):
        return reverse_lazy('expense:expense_detail', kwargs={'pk': self.pk})

    def get_fields_verbose_names(self):
        return [{'name': field.verbose_name, 'value': getattr(self, field.name)} for field in self._meta.fields]

expense/forms.py
from django import forms

from .models import Expense


class ExpenseForm(forms.ModelForm):
    required_css_class = 'required'

    payment_date = forms.DateField(
        label='Data de pagamento',
        widget=forms.DateInput(
            format='%Y-%m-%d',
            attrs={
                'type': 'date',
            }),
        input_formats=('%Y-%m-%d',),
        required=False,
    )

    class Meta:
        model = Expense
        fields = ('description', 'payment_date', 'person', 'value', 'paid')

    def __init__(self, *args, **kwargs):
        super(ExpenseForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
        self.fields['paid'].widget.attrs['class'] = None

expense/views.py
from django.shortcuts import render
from django.views.decorators.http import require_http_methods
from django.views.generic import ListView

from .forms import ExpenseForm
from .mixins import SearchExpenseMixin
from .models import Expense


class ExpenseListView(SearchExpenseMixin, ListView):
    model = Expense
    paginate_by = 10


def expense_detail(request, pk):
    template_name = 'expense/expense_detail.html'
    obj = Expense.objects.get(pk=pk)
    context = {'object': obj}
    return render(request, template_name, context)


def expense_create(request):
    template_name = 'expense/expense_form.html'
    form = ExpenseForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            expense = form.save()
            template_name = 'expense/expense_result.html'
            context = {'object': expense}
            return render(request, template_name, context)

    context = {'form': form}
    return render(request, template_name, context)


def expense_update(request, pk):
    template_name = 'expense/expense_update_form.html'
    instance = Expense.objects.get(pk=pk)
    form = ExpenseForm(request.POST or None, instance=instance)

    if request.method == 'POST':
        if form.is_valid():
            expense = form.save()
            template_name = 'expense/expense_result.html'
            context = {'object': expense}
            return render(request, template_name, context)

    context = {'form': form, 'object': instance}
    return render(request, template_name, context)


@require_http_methods(['DELETE'])
def expense_delete(request, pk):
    template_name = 'expense/expense_table.html'
    obj = Expense.objects.get(pk=pk)
    obj.delete()
    return render(request, template_name)

expense/templates/expense/expense_detail.html
<div class="modal-header">
  <h4 class="modal-title" id="detailModalLabel">{{ object.description }}</h4>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
</div>
<div class="modal-body">
  <p>Pago a
    <span class="float-right">{{ object.person|default:'---' }}</span>
  </p>
  <p>Valor
    <span class="float-right">{{ object.value }}</span>
  </p>
  <p>Data de pagamento
    <span class="float-right">{{ object.payment_date|date:'d/m/Y'|default:'---' }}</span>
  </p>
  <p>Pago
    <span class="float-right">
      {% if object.paid %}
        <i class="fa fa-check-circle ok"></i>
      {% else %}
        <i class="fa fa-times-circle no"></i>
      {% endif %}
    </span>
  </p>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
</div>

expense/templates/expense/expense_form.html
<div class="modal-header">
  <h4 class="modal-title" id="addModalLabel">Adicionar</h4>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
</div>
<form
  hx-post="{% url 'expense:expense_create' %}"
  hx-target="#expenseTbody"
  hx-indicator=".htmx-indicator"
  hx-swap="afterbegin"
>
  <div class="modal-body">
    {% csrf_token %}
    {% for field in form %}
      <div class="form-group p-2">
        {{ field.label_tag }}
        {{ field }}
        {{ field.errors }}
        {% if field.help_text %}
          <small class="text-muted">{{ field.help_text|safe }}</small>
        {% endif %}
      </div>
    {% endfor %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
    <button type="submit" class="btn btn-primary">Salvar</button>
  </div>
</form>

<script>
  $('form').on('submit', function() {
    $('#addModal').modal('toggle')
  });
</script>

expense/templates/expense/expense_list.html
<!-- expense_list.html -->
{% extends "base.html" %}

{% block content %}
<div>
  <div class="row">
    <div class="col-auto">
      <h1>Lista de Despesas</h1>
    </div>
    <div class="col-auto">
      <a
        href=""
        class="btn btn-primary"
        data-toggle="modal"
        data-target="#addModal"
        hx-get="{% url 'expense:expense_create' %}"
        hx-target="#addContent"
        hx-swap="innerHTML"
      >Adicionar</a>
    </div>
    <div class="col">
      <form action="." method="GET" class="form-inline">
        <div class="form-group flex-grow-1">
          <input id="id_search" name="search" class="form-control flex-grow-1" type="text" placeholder="Buscar..." />
        </div>
        <div class="form-group pl-2">
          <button type="submit" class="btn btn-success">Buscar</button>
        </div>
        <div class="form-group pl-2">
          <a class="btn btn-link" href=".">Limpar</a>
        </div>
      </form>
    </div>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th>Descrição</th>
        <th>Pago a</th>
        <th>Valor</th>
        <th>Data de pagamento</th>
        <th>Pago?</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody id="expenseTbody">
      {% include "./expense_table.html" %}
    </tbody>
  </table>
</div>

{% include "includes/pagination.html" %}

{% include "./includes/detail_modal.html" %}
{% include "./includes/add_modal.html" %}
{% include "./includes/update_modal.html" %}

{% endblock content %}

{% block js %}
<script>
// Necessário por causa do delete
document.body.addEventListener('htmx:configRequest', (event) => {
  event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
});
</script>
{% endblock js %}

expense/templates/expense/expense_result.html
<!-- expense_result.html -->
<tr id="trExpense{{ object.pk }}">
  <td>
    <a
      href=""
      data-toggle="modal"
      data-target="#detailModal"
      hx-get="{{ object.get_absolute_url }}"
      hx-target="#detailContent"
      hx-indicator=".htmx-indicator"
      hx-swap="innerHTML"
    >{{ object.description }}</a>
  </td>
  <td>{{ object.person|default:'---' }}</td>
  <td>{{ object.value }}</td>
  <td>{{ object.payment_date|date:'d/m/Y'|default:'---' }}</td>
  <td>
    <span class="text-center">
      {% if object.paid %}
        <i class="fa fa-check-circle ok"></i>
      {% else %}
        <i class="fa fa-times-circle no"></i>
      {% endif %}
    </span>
  </td>
  <td>
    <span
      data-toggle="modal"
      data-target="#updateModal"
      hx-get="{% url 'expense:expense_update' object.pk %}"
      hx-target="#updateContent"
      hx-swap="innerHTML"
    >
      <i class="fa fa-edit link span-is-link"></i>
    </span>
    <span
      hx-delete="{% url 'expense:expense_delete' object.pk %}"
      hx-confirm="Deseja mesmo deletar?"
      hx-target="closest tr"
      hx-swap="outerHTML swap:500ms"
    >
      <i class="fa fa-trash no span-is-link pl-2"></i>
    </span>
  </td>
</tr>

expense/templates/expense/expense_table.html
<!-- expense_table.html -->
{% for object in object_list %}
  {% include "./expense_result.html" %}
{% endfor %}

expense/templates/expense/expense_update_form.html
<div class="modal-header">
  <h4 class="modal-title" id="updateModalLabel">Editar {{ object }}</h4>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
</div>
<form
  hx-post="{% url 'expense:expense_update' object.pk %}"
  hx-target="#trExpense{{ object.pk }}"
  hx-indicator=".htmx-indicator"
  hx-swap="outerHTML"
>
  <div class="modal-body">
    {% csrf_token %}
    {% for field in form %}
      <div class="form-group p-2">
        {{ field.label_tag }}
        {{ field }}
        {{ field.errors }}
        {% if field.help_text %}
          <small class="text-muted">{{ field.help_text|safe }}</small>
        {% endif %}
      </div>
    {% endfor %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
    <button type="submit" class="btn btn-primary">Salvar</button>
  </div>
</form>

<script>
  $('form').on('submit', function() {
    $('#updateModal').modal('toggle')
  });
</script>

expense/templates/expense/includes/add_modal.html
<!-- addModal -->
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="addModalLabel">
  <div class="modal-dialog" role="document">
    <div id="addContent" class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="detailModalLabel">Modal title</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button type="submit" class="btn btn-primary">Salvar</button>
      </div>
    </div>
  </div>
</div>

expense/templates/expense/includes/detail_modal.html
<!-- detailModal -->
<div class="modal fade" id="detailModal" tabindex="-1" role="dialog" aria-labelledby="detailModalLabel">
  <div class="modal-dialog" role="document">
    <div id="detailContent" class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="detailModalLabel">Modal title</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button type="submit" class="btn btn-primary">Salvar</button>
      </div>
    </div>
  </div>
</div>

expense/templates/expense/includes/update_modal.html
<!-- updateModal -->
<div class="modal fade" id="updateModal" tabindex="-1" role="dialog" aria-labelledby="updateModalLabel">
  <div class="modal-dialog" role="document">
    <div id="updateContent" class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="updateModalLabel">Modal title</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button type="submit" class="btn btn-primary">Salvar</button>
      </div>
    </div>
  </div>
</div>